services:
  db:
    image: postgres:16-alpine
    container_name: ltm_postgres
    environment:
      POSTGRES_USER: line
      POSTGRES_PASSWORD: line
      POSTGRES_DB: line_task_manager
    ports:
      - "5432:5432"
    volumes:
      - ltm_pgdata:/var/lib/postgresql/data

volumes:
  ltm_pgdata:
